<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="27" total="28" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-10-19T16:41:07 MSK" name="All Test Suite" finished-at="2023-10-19T16:42:13 MSK" duration-ms="66032">
    <groups>
    </groups>
    <test started-at="2023-10-19T16:41:07 MSK" name="/Users/ruslanfursa/IdeaProjects/Orange" finished-at="2023-10-19T16:42:13 MSK" duration-ms="66032">
      <class name="runner.TimeTest">
        <test-method is-config="true" signature="init()[pri:0, instance:runner.TimeTest@38145825]" started-at="2023-10-19T16:41:08 MSK" name="init" finished-at="2023-10-19T16:41:18 MSK" duration-ms="9862" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method is-config="true" signature="openSite()[pri:0, instance:runner.TimeTest@38145825]" started-at="2023-10-19T16:41:18 MSK" name="openSite" finished-at="2023-10-19T16:41:22 MSK" duration-ms="4108" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openSite -->
        <test-method signature="testToggles()[pri:0, instance:runner.TimeTest@38145825]" started-at="2023-10-19T16:41:22 MSK" name="testToggles" finished-at="2023-10-19T16:42:08 MSK" duration-ms="45758" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertTrue(Assert.java:56)
at org.testng.Assert.assertTrue(Assert.java:66)
at runner.TimeTest.testToggles(TimeTest.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testToggles -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:runner.TimeTest@38145825]" started-at="2023-10-19T16:42:13 MSK" name="quitDriver" finished-at="2023-10-19T16:42:13 MSK" duration-ms="161" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
      </class> <!-- runner.TimeTest -->
    </test> <!-- /Users/ruslanfursa/IdeaProjects/Orange -->
  </suite> <!-- All Test Suite -->
</testng-results>
